### ISSUE TITLE
Error when installing from requirements.txt

### ISSUE THREAD

**Issue by Hubblenaut** [erichson/SuperBench#4]
Running `pip install -r requirements.txt` yields the error:
```
ERROR: Invalid requirement: 'torchvision~=0.9.1+cu101' (from line 11 of requirements.txt)
```

When iteratively removing the requirements that cause issues from the requirements file, I still get the following errors:
```
ERROR: Could not find a version that satisfies the requirement Python~=3.9.15 (from versions: none)
ERROR: No matching distribution found for Python~=3.9.15
```
```
ERROR: Could not find a version that satisfies the requirement decimal~=1.70 (from versions: none)
ERROR: No matching distribution found for decimal~=1.70
```

For some reason, I am unable to find the correct versions for these packages. Is there an installation step I am missing?

**Comment by erichson** [comment]
Can you try this again? I cannot reproduce this issue.
